### ISSUE TITLE
Not getting a friend code after disabling HTTP

### ISSUE THREAD

**Issue by squarepizza1** [PabloMK7/citra#122] opened 2024-05-14 20:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

71eca05

### Description of Issue

The friends list says my friend code is ????-????-???? and won't let me play online.

### Expected Behavior

An actual friend code.

### Reproduction Steps

Open friends list

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/15313532/citra_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by everypizza1** [comment] 2024-05-15 23:00
Nintendo has [shut down online services](https://en-americas-support.nintendo.com/app/answers/detail/a_id/63227/~/announcement-of-discontinuation-of-online-services-for-nintendo-3ds-and-wii-u) for the 3DS.

**Comment by Radu13** [comment] 2024-05-16 08:38
> Nintendo has [shut down online services](https://en-americas-support.nintendo.com/app/answers/detail/a_id/63227/~/announcement-of-discontinuation-of-online-services-for-nintendo-3ds-and-wii-u) for the 3DS.

That's not relevant, I can confirm with an older Citra version of this fork I can succesfully download system files, enable all LLE modules needed (including http) and after making a mii friend code will indeed be generated

**Comment by squarepizza1** [comment] 2024-06-25 01:10
I'm still having this issue one month later. I really hope that this is fixed eventually.

**Comment by PabloMK7** [comment] 2024-07-09 19:54
Closing as the issue is probably caused by misplacement of files.

**Closed by PabloMK7** 2024-07-09 19:54 UTC

**Comment by squarepizza1** [comment] 2024-07-11 03:19
Where do I place the files? Citra is able to load them and If I have HTTP enabled, I can use the 3ds web browser.
