### ISSUE TITLE
Friends List softlock

### ISSUE THREAD

**Issue by squarepizza1** [PabloMK7/citra#117] opened 2024-05-14 04:19 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

71eca05

### Description of Issue

Opening the friends list while connected to Pretendo softlocks Citra. Trying to play any games online will instanly disconnect me.

### Expected Behavior

Getting a friend code.

### Reproduction Steps

Open the friends list.

### Log File

[citra_log.txt](https://github.com/PabloMK7/citra/files/15302548/citra_log.txt)

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by PabloMK7** [comment] 2024-05-14 06:26
This is a bug caused by Pretendo http patch, duplicate of https://github.com/PretendoNetwork/nimbus/issues/39

**Closed by PabloMK7** 2024-05-14 06:26 UTC
