### ISSUE TITLE
Smash Bros. for Nintendo 3DS - Vulkan Backend- Fullscreen crashes program on Steam Deck/Linux Build

### ISSUE THREAD

**Issue by drewbyhk** [PabloMK7/citra#38] opened 2024-03-19 14:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

r8433057

### Description of Issue

Whenever Citra is toggled to fullscreen mode, it causes the program to crash.

### Expected Behavior

Fullscreen should work just fine and allow the user to play games without crashing

### Reproduction Steps

1. Open Citra
2. Select a game
3. Go to View > Fullscreen and toggle fullscreen
4. Program crashes.

### Log File

Not sure how to pull the log file from Linux. If anyone knows, please let me know and I can upload a log.

### System Configuration

Using 256GB LCD Steam Deck

**Comment by Miguel-hrvs** [comment] 2024-03-19 15:51
Go to .local/share/citra-emu/log and post your citra_log.txt
In my pc I can't reproduce the issue.

**Comment by drewbyhk** [comment] 2024-03-19 15:54
[citra_log.txt](https://github.com/PabloMK7/citra/files/14653050/citra_log.txt)
Here is my log file.

**Comment by Miguel-hrvs** [comment] 2024-03-19 15:58
Thanks, does it happen on any renderer?

**Comment by Miguel-hrvs** [comment] 2024-03-19 16:21
In citra-ufork this doesn't happen

**Comment by drewbyhk** [comment] 2024-03-19 16:34
Did a bit more testing. I also came to the same conclusion, since it doesn't happen on OpenGL. 

Also, it seems other games are unaffected. Seems like a Smash Bros. exclusive issue.

**Comment by rtiangha** [comment] 2024-04-12 19:02
Oh, weird. Smash Bros full screen works in the last Canary, but it does NOT work in the last nightly (r2104). I don't know what that implies.

**Comment by rtiangha** [comment] 2024-04-12 19:25
And it doesn't work in v2.2 either.

**Comment by Miguel-hrvs** [comment] 2024-04-13 11:40
Yep, it was fixed on the last rafaelthegreat vulkan canary changes.

**Comment by rtiangha** [comment] 2024-04-13 17:19
Do you know what commit that is? I'd like to merge that into my fork.

**Comment by Miguel-hrvs** [comment] 2024-04-13 19:27
You have to include these I think: https://github.com/PabloMK7/citra/pull/27/commits/9f5c8d0e2f5db880082bbd20518da7b60bb4db3f
https://github.com/PabloMK7/citra/pull/27/commits/4a63fc2ca2e47f08532fb44e23a4857fc4339d07
https://github.com/PabloMK7/citra/pull/27/commits/0c9037f075ca6c0bbf8a5fc542c47a30aefdf551

**Comment by rtiangha** [comment] 2024-04-14 13:17
The semaphore one was also part of that set, and with a minor change to match current code to get it to compile, you're right; it fixed the problem. I've submitted Pull Request #77.

**Comment by Miguel-hrvs** [comment] 2024-04-14 14:07
Good work! This is an important fix for linux and macos

**Comment by rtiangha** [comment] 2024-04-22 23:39
It's been merged now.

https://github.com/PabloMK7/citra/releases/tag/ra8e601a

**Closed** 2024-07-09 19:57 UTC
