### ISSUE TITLE
Online Updates

### ISSUE THREAD

**Issue by Gabrielcnnunes** [PabloMK7/citra#214] opened 2024-07-24 22:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

How about add an online update to Citra MK7 like original Citra had?

### Why would this feature be useful?

Update the system in few seconds.

**Comment by PabloMK7** [comment] 2024-07-25 06:33
Hello, duplicate of #31

**Closed by PabloMK7** 2024-07-25 06:33 UTC
