### ISSUE TITLE
Some network connection issues during playing pokemon

### ISSUE THREAD

**Issue by liketolike** [PabloMK7/citra#7] opened 2023-11-14 17:31 UTC
Currently playing X and OR,I will test USUM after a while
1.Cannot free battle in Battle Spot,Prompt:No data found on the server, please try again later.
2.I couldn't find each other on the passerby list using 3DS and emulator. I traded through GTS to make it appear on the list of acquaintances,
and can't battle, but can trade.
3.Wonder trading may experience a soft lock when discovering a trading partner, but after restarting the emulator, it is discovered that the transaction is complete,attach log.

**Comment by liketolike** [comment] 2023-11-14 17:31
[citra_log.txt.old.txt](https://github.com/PabloMK7/citra/files/13352559/citra_log.txt.old.txt)

**Comment by Justin-ojay** [comment] 2023-11-19 22:20
I have a sysnand.bin file from a 3ds XL in my android files , does anyone know how to extract the console unique codes from it

**Comment by PabloMK7** [comment] 2023-11-20 08:55
This is caused by missing BOSS, will be fixed in the next release

**Comment by Justin-ojay** [comment] 2023-11-20 10:48
How do I connect online on the 3ds home menu

**Comment by liketolike** [comment] 2023-11-24 16:05
> This is caused by missing BOSS, will be fixed in the next release
I'm looking forward to it

**Comment by liketolike** [comment] 2023-11-24 16:10
> How do I connect online on the 3ds home menu

I followed the installation instructions and he worked very well

**Comment by PabloMK7** [comment] 2024-01-14 00:56
Fixed

**Closed by PabloMK7** 2024-01-14 00:56 UTC
